// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: grpc/proto/service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContactID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactID) Reset() {
	*x = ContactID{}
	mi := &file_grpc_proto_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactID) ProtoMessage() {}

func (x *ContactID) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactID.ProtoReflect.Descriptor instead.
func (*ContactID) Descriptor() ([]byte, []int) {
	return file_grpc_proto_service_proto_rawDescGZIP(), []int{0}
}

func (x *ContactID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Contact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *ContactID             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Firstname     string                 `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname      string                 `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_grpc_proto_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_grpc_proto_service_proto_rawDescGZIP(), []int{1}
}

func (x *Contact) GetId() *ContactID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Contact) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *Contact) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_grpc_proto_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_grpc_proto_service_proto_rawDescGZIP(), []int{2}
}

var File_grpc_proto_service_proto protoreflect.FileDescriptor

const file_grpc_proto_service_proto_rawDesc = "" +
	"\n" +
	"\x18grpc/proto/service.proto\"\x1b\n" +
	"\tContactID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"_\n" +
	"\aContact\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\v2\n" +
	".ContactIDR\x02id\x12\x1c\n" +
	"\tfirstname\x18\x02 \x01(\tR\tfirstname\x12\x1a\n" +
	"\blastname\x18\x03 \x01(\tR\blastname\"\a\n" +
	"\x05Empty2}\n" +
	"\aService\x12&\n" +
	"\x0eContactsCreate\x12\b.Contact\x1a\n" +
	".ContactID\x12$\n" +
	"\fContactsRead\x12\n" +
	".ContactID\x1a\b.Contact\x12$\n" +
	"\x0eContactsDelete\x12\n" +
	".ContactID\x1a\x06.EmptyB\tZ\a./protob\x06proto3"

var (
	file_grpc_proto_service_proto_rawDescOnce sync.Once
	file_grpc_proto_service_proto_rawDescData []byte
)

func file_grpc_proto_service_proto_rawDescGZIP() []byte {
	file_grpc_proto_service_proto_rawDescOnce.Do(func() {
		file_grpc_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_proto_service_proto_rawDesc), len(file_grpc_proto_service_proto_rawDesc)))
	})
	return file_grpc_proto_service_proto_rawDescData
}

var file_grpc_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpc_proto_service_proto_goTypes = []any{
	(*ContactID)(nil), // 0: ContactID
	(*Contact)(nil),   // 1: Contact
	(*Empty)(nil),     // 2: Empty
}
var file_grpc_proto_service_proto_depIdxs = []int32{
	0, // 0: Contact.id:type_name -> ContactID
	1, // 1: Service.ContactsCreate:input_type -> Contact
	0, // 2: Service.ContactsRead:input_type -> ContactID
	0, // 3: Service.ContactsDelete:input_type -> ContactID
	0, // 4: Service.ContactsCreate:output_type -> ContactID
	1, // 5: Service.ContactsRead:output_type -> Contact
	2, // 6: Service.ContactsDelete:output_type -> Empty
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_proto_service_proto_init() }
func file_grpc_proto_service_proto_init() {
	if File_grpc_proto_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_proto_service_proto_rawDesc), len(file_grpc_proto_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_service_proto_goTypes,
		DependencyIndexes: file_grpc_proto_service_proto_depIdxs,
		MessageInfos:      file_grpc_proto_service_proto_msgTypes,
	}.Build()
	File_grpc_proto_service_proto = out.File
	file_grpc_proto_service_proto_goTypes = nil
	file_grpc_proto_service_proto_depIdxs = nil
}
